require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MorePowerUpsRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # MorePowerUpsRequest. As you add validations to MorePowerUpsRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MorePowerUpsRequestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all more_power_ups_requests as @more_power_ups_requests" do
      more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:more_power_ups_requests).should eq([more_power_ups_request])
    end
  end

  describe "GET show" do
    it "assigns the requested more_power_ups_request as @more_power_ups_request" do
      more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
      get :show, {:id => more_power_ups_request.to_param}, valid_session
      assigns(:more_power_ups_request).should eq(more_power_ups_request)
    end
  end

  describe "GET new" do
    it "assigns a new more_power_ups_request as @more_power_ups_request" do
      get :new, {}, valid_session
      assigns(:more_power_ups_request).should be_a_new(MorePowerUpsRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested more_power_ups_request as @more_power_ups_request" do
      more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
      get :edit, {:id => more_power_ups_request.to_param}, valid_session
      assigns(:more_power_ups_request).should eq(more_power_ups_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MorePowerUpsRequest" do
        expect {
          post :create, {:more_power_ups_request => valid_attributes}, valid_session
        }.to change(MorePowerUpsRequest, :count).by(1)
      end

      it "assigns a newly created more_power_ups_request as @more_power_ups_request" do
        post :create, {:more_power_ups_request => valid_attributes}, valid_session
        assigns(:more_power_ups_request).should be_a(MorePowerUpsRequest)
        assigns(:more_power_ups_request).should be_persisted
      end

      it "redirects to the created more_power_ups_request" do
        post :create, {:more_power_ups_request => valid_attributes}, valid_session
        response.should redirect_to(MorePowerUpsRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved more_power_ups_request as @more_power_ups_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        MorePowerUpsRequest.any_instance.stub(:save).and_return(false)
        post :create, {:more_power_ups_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:more_power_ups_request).should be_a_new(MorePowerUpsRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MorePowerUpsRequest.any_instance.stub(:save).and_return(false)
        post :create, {:more_power_ups_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested more_power_ups_request" do
        more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
        # Assuming there are no other more_power_ups_requests in the database, this
        # specifies that the MorePowerUpsRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MorePowerUpsRequest.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => more_power_ups_request.to_param, :more_power_ups_request => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested more_power_ups_request as @more_power_ups_request" do
        more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
        put :update, {:id => more_power_ups_request.to_param, :more_power_ups_request => valid_attributes}, valid_session
        assigns(:more_power_ups_request).should eq(more_power_ups_request)
      end

      it "redirects to the more_power_ups_request" do
        more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
        put :update, {:id => more_power_ups_request.to_param, :more_power_ups_request => valid_attributes}, valid_session
        response.should redirect_to(more_power_ups_request)
      end
    end

    describe "with invalid params" do
      it "assigns the more_power_ups_request as @more_power_ups_request" do
        more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MorePowerUpsRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => more_power_ups_request.to_param, :more_power_ups_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:more_power_ups_request).should eq(more_power_ups_request)
      end

      it "re-renders the 'edit' template" do
        more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MorePowerUpsRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => more_power_ups_request.to_param, :more_power_ups_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested more_power_ups_request" do
      more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => more_power_ups_request.to_param}, valid_session
      }.to change(MorePowerUpsRequest, :count).by(-1)
    end

    it "redirects to the more_power_ups_requests list" do
      more_power_ups_request = MorePowerUpsRequest.create! valid_attributes
      delete :destroy, {:id => more_power_ups_request.to_param}, valid_session
      response.should redirect_to(more_power_ups_requests_url)
    end
  end

end
